export const STARTED_ADD_USER = 'STARTED_ADD_USER'
export const ENDED_ADD_USER = 'ENDED_ADD_USER'

export const STARTED_REMOVE_USER = 'STARTED_REMOVE_USER'
export const ENDED_REMOVE_USER = 'ENDED_REMOVE_USER'

export const STARTED_SHOW_NOTIFICATION = 'STARTED_SHOW_NOTIFICATION'
export const ENDED_SHOW_NOTIFICATION = 'ENDED_SHOW_NOTIFICATION'

export const STARTED_FETCH_TECHNOLOGIES = 'STARTED_FETCH_TECHNOLOGIES'
export const ENDED_FETCH_TECHNOLOGIES = 'ENDED_FETCH_TECHNOLOGIES'
