export const REQUESTED_INSTRUCTOR = 'REQUESTED_INSTRUCTOR'
export const RECEIVED_INSTRUCTOR = 'RECEIVED_INSTRUCTOR'

export const REQUESTED_INSTRUCTOR_LESSONS = 'REQUESTED_INSTRUCTOR_LESSONS'
export const RECEIVED_INSTRUCTOR_LESSONS = 'RECEIVED_INSTRUCTOR_LESSONS'

export const REQUESTED_ALL_LESSONS = 'REQUESTED_ALL_LESSONS'
export const RECEIVED_ALL_LESSONS = 'RECEIVED_ALL_LESSONS'

export const STARTED_UPDATE_LESSON_STATE = 'STARTED_UPDATE_LESSON_STATE'
export const ENDED_UPDATE_LESSON_STATE = 'ENDED_UPDATE_LESSON_STATE'
