export const STARTED_FETCH_INSTRUCTOR = 'STARTED_FETCH_INSTRUCTOR'
export const ENDED_FETCH_INSTRUCTOR = 'ENDED_FETCH_INSTRUCTOR'

export const STARTED_FETCH_INSTRUCTOR_LESSONS = 'STARTED_FETCH_INSTRUCTOR_LESSONS'
export const ENDED_FETCH_INSTRUCTOR_LESSONS = 'ENDED_FETCH_INSTRUCTOR_LESSONS'

export const STARTED_FETCH_ALL_LESSONS = 'STARTED_FETCH_ALL_LESSONS'
export const ENDED_FETCH_ALL_LESSONS = 'ENDED_FETCH_ALL_LESSONS'

export const STARTED_UPDATE_LESSON_STATE = 'STARTED_UPDATE_LESSON_STATE'
export const ENDED_UPDATE_LESSON_STATE = 'ENDED_UPDATE_LESSON_STATE'

export const STARTED_SUBMIT_LESSON = 'STARTED_SUBMIT_LESSON'
export const ENDED_SUBMIT_LESSON = 'ENDED_SUBMIT_LESSON'

export const STARTED_FETCH_TECHNOLOGIES = 'STARTED_FETCH_TECHNOLOGIES'
export const ENDED_FETCH_TECHNOLOGIES = 'ENDED_FETCH_TECHNOLOGIES'
