export const STARTED_FETCH_INSTRUCTOR = 'STARTED_FETCH_INSTRUCTOR'
export const ENDED_FETCH_INSTRUCTOR = 'ENDED_FETCH_INSTRUCTOR'

export const STARTED_FETCH_INSTRUCTOR_LESSONS = 'STARTED_FETCH_INSTRUCTOR_LESSONS'
export const ENDED_FETCH_INSTRUCTOR_LESSONS = 'ENDED_FETCH_INSTRUCTOR_LESSONS'

export const STARTED_FETCH_ALL_LESSONS = 'STARTED_FETCH_ALL_LESSONS'
export const ENDED_FETCH_ALL_LESSONS = 'ENDED_FETCH_ALL_LESSONS'
